### ISSUE TITLE
Segfault on rocket frag in warmup

### ISSUE THREAD

**Issue by joe0x04** [packetflinger/openra2#8]
Didn't happen with railgun, only rocket, and I'm pretty sure it was splash damage that triggered the frag.

I haven't been able to get a backtrace on this, but it happened twice while testing with kapolsky.

**Comment by joe0x04** [comment]
Finally was able to catch it in the wild:
```
claire almost dodged horsedick.MPEG's rocket
]
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7db7529 in player_die (self=0x96c2b8, inflictor=0x99f740,
    attacker=0x96c2b8, damage=30, point=0x99f744) at p_client.c:611
611                     self->client->pers.team->players_alive--;
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.209.el6_9.2.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) backtrace
#0  0x00007ffff7db7529 in player_die (self=0x96c2b8, inflictor=0x99f740,
    attacker=0x96c2b8, damage=30, point=0x99f744) at p_client.c:611
#1  0x00007ffff7d95ee4 in Killed (targ=0x96c2b8, inflictor=0x99f740,
    attacker=0x96c2b8, damage=30, point=0x99f744) at g_combat.c:101
#2  0x00007ffff7d96982 in T_Damage (targ=0x96c2b8, inflictor=0x99f740,
    attacker=0x96c2b8, dir=0x7fffffffe230, point=0x99f744,
    normal=0x7ffff7fdf720, damage=30, knockback=30, dflags=1, mod=9)
    at g_combat.c:406
#3  0x00007ffff7d96dce in T_RadiusDamage (inflictor=0x99f740,
    attacker=0x96c2b8, damage=120, ignore=0x96bef0, radius=120, mod=9)
    at g_combat.c:459
#4  0x00007ffff7db48c8 in rocket_touch (ent=0x99f740, other=0x96bef0,
    plane=0x7fffffffe3d8, surf=0x7ffff7a43808) at g_weapon.c:455
#5  0x00007ffff7da823b in SV_Impact (e1=0x99f740, trace=0x7fffffffe3c0)
    at g_phys.c:127
#6  0x00007ffff7da8657 in SV_PushEntity (ent=0x99f740, push=0x7fffffffe4a0)
    at g_phys.c:216
#7  0x00007ffff7da97a4 in SV_Physics_Toss (ent=0x99f740) at g_phys.c:560
#8  0x00007ffff7da9bef in G_RunEntity (ent=0x99f740) at g_phys.c:635
#9  0x00007ffff7da26af in G_RunFrame () at g_main.c:799
#10 0x000000000042772f in SV_RunGameFrame (msec=<value optimized out>)
    at src/server/main.c:1710
#11 SV_Frame (msec=<value optimized out>) at src/server/main.c:1864
#12 0x0000000000408cb6 in Qcommon_Frame () at src/common/common.c:1131
#13 0x000000000042c464 in main (argc=8, argv=0x7fffffffe6c8)
    at src/unix/system.c:479
```

**Comment by joe0x04** [comment]
Erik and I played a bunch of matches today and no crash.
